name: Deploy to dev

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Enter the tag to deploy (e.g., v1.0.0)'
        required: true

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}  # Use the selected tag
      # Your other build steps here

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      # Your deployment steps here
